// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// /// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return web configuration when running on web
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd_F9D0TxbiHXilpgCszghj4hKlJYbGHU',
    appId: "1:415377246287:android:6a990a98de18e7addb023a",
    messagingSenderId: '415377246287',
    projectId: 'carvy-test',
    storageBucket: 'carvy-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0uCmoNbNm0E1DsuP0gZIlgue9ePX0tG0',
    appId: '1:415377246287:ios:8eee51c7ed29b162db023a',
    messagingSenderId: '415377246287',
    projectId: 'carvy-test',
    storageBucket: 'carvy-test.firebasestorage.app',
    iosClientId:
        '415377246287-knvcq59kbb9j4nn27aogt5j3qg94imi3.apps.googleusercontent.com',
    iosBundleId: 'com.carvy.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDJmfSsQoJwx9OCf6t3m-0tcXNT6NilbcI",
      authDomain: "carvyvehicle.firebaseapp.com",
      databaseURL: "https://carvyvehicle-default-rtdb.firebaseio.com",
      projectId: "carvyvehicle",
      storageBucket: "carvyvehicle.appspot.com",
      messagingSenderId: "951328556833",
      appId: "1:951328556833:web:4a922ffcaa3df4341de060");
}
